name: core
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  external_dependencies:
    git:
      url: https://github.com/euclidesgc/external_dependencies.git
      ref: v1.0.0
  config_module:
    git:
      url: https://github.com/euclidesgc/config_module.git
      ref: v1.0.0
  contact_us_module:
    git:
      url: https://github.com/euclidesgc/contact_us_module.git
      ref: v1.0.0
  dashboard_module:
    git:
      url: https://github.com/euclidesgc/dashboard_module.git
      ref: v1.0.0
  data_bank_module:
    git:
      url: https://github.com/euclidesgc/data_bank_module.git
      ref: v1.0.0
  financial_module:
    git:
      url: https://github.com/euclidesgc/financial_module.git
      ref: v1.0.0
  home_module:
    git:
      url: https://github.com/euclidesgc/home_module.git
      ref: v1.0.0
  my_store_module:
    git:
      url: https://github.com/euclidesgc/my_store_module.git
      ref: v1.0.0
  order_module:
    git:
      url: https://github.com/euclidesgc/order_module.git
      ref: v1.0.0
  partner_list_module:
    git:
      url: https://github.com/euclidesgc/partner_list_module.git
      ref: v1.0.0
  policies_and_privacy_module:
    git:
      url: https://github.com/euclidesgc/policies_and_privacy_module.git
      ref: v1.0.0
  product_module:
    git:
      url: https://github.com/euclidesgc/product_module.git
      ref: v1.0.0
  qanda_module:
    git:
      url: https://github.com/euclidesgc/qanda_module.git
      ref: v1.0.0
  splash_module:
    git:
      url: https://github.com/euclidesgc/splash_module.git
      ref: v1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
